package models;

import java.io.Serializable;


/**
* CorbaModule/Project.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Tuesday, October 23, 2018 at 9:46:16 PM Eastern Daylight Time
*/

public final class Project implements Serializable
{
  private String projectId;
  private String clientName;
  private String projectName;

  public Project ()
  {
  } // ctor

  public Project (String _projectId, String _clientName, String _projectName)
  {
    projectId = _projectId;
    clientName = _clientName;
    projectName = _projectName;
  } // ctor

	public String getProjectId() {
		return projectId;
	}

	public String getClientName() {
		return clientName;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectId(String id) {
		this.projectId = id;
	}

	public void setClientName(String cName) {
		this.clientName = cName;
	}

	public void setProjectName(String pName) {
		this.projectName = pName;
	}

} // class Project
