package CorbaModule;


/**
* CorbaModule/ManagerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Tuesday, October 23, 2018 at 9:46:16 PM Eastern Daylight Time
*/

public abstract class ManagerInterfacePOA extends org.omg.PortableServer.Servant
 implements CorbaModule.ManagerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createMRecord", new java.lang.Integer (0));
    _methods.put ("createERecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("transferRecord", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaModule/ManagerInterface/createMRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String employeeID = in.read_string ();
         String mailID = in.read_string ();
         CorbaModule.Project project = CorbaModule.ProjectHelper.read (in);
         String location = in.read_string ();
         String $result = null;
         $result = this.createMRecord (managerID, firstName, lastName, employeeID, mailID, project, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CorbaModule/ManagerInterface/createERecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         short employeeID = in.read_short ();
         String mailID = in.read_string ();
         String projectId = in.read_string ();
         String $result = null;
         $result = this.createERecord (managerID, firstName, lastName, employeeID, mailID, projectId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CorbaModule/ManagerInterface/getRecordCounts
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CorbaModule/ManagerInterface/editRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editRecord (managerID, recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CorbaModule/ManagerInterface/transferRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String remoteCenterServerName = in.read_string ();
         String $result = null;
         $result = this.transferRecord (managerID, recordID, remoteCenterServerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaModule/ManagerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ManagerInterface _this() 
  {
    return ManagerInterfaceHelper.narrow(
    super._this_object());
  }

  public ManagerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ManagerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ManagerInterfacePOA
