package CorbaModule;


/**
* CorbaModule/ManagerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Tuesday, October 23, 2018 at 9:46:16 PM Eastern Daylight Time
*/

public interface ManagerInterface extends ManagerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
	
} // interface ManagerInterface
