package CorbaModule;


/**
* CorbaModule/ManagerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Tuesday, October 23, 2018 at 9:46:16 PM Eastern Daylight Time
*/

public interface ManagerInterfaceOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, String employeeID, String mailID, CorbaModule.Project project, String location);
  String createERecord (String managerID, String firstName, String lastName, short employeeID, String mailID, String projectId);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface ManagerInterfaceOperations
