package CorbaModule;


/**
* CorbaModule/ManagerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Monday, October 22, 2018 6:50:23 PM EDT
*/

public interface ManagerInterface extends ManagerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ManagerInterface
