package CorbaModule;


/**
* CorbaModule/ManagerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Monday, October 22, 2018 6:50:23 PM EDT
*/

public interface ManagerInterfaceOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, String employeeID, String mailID, CorbaModule.Project project, String location);
  String createERecord (String managerID, String firstName, String lastName, short employeeID, String mailID, String projectId);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  void printData (String managerID, String init, String serverLocation, boolean isSuccess, String task);
  String getMapCount ();
} // interface ManagerInterfaceOperations
