package CorbaModule;


/**
* CorbaModule/ManagerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Tuesday, October 23, 2018 at 9:46:16 PM Eastern Daylight Time
*/

abstract public class ManagerInterfaceHelper
{
  private static String  _id = "IDL:CorbaModule/ManagerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaModule.ManagerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaModule.ManagerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaModule.ManagerInterfaceHelper.id (), "ManagerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaModule.ManagerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ManagerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaModule.ManagerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaModule.ManagerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaModule.ManagerInterface)
      return (CorbaModule.ManagerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaModule._ManagerInterfaceStub stub = new CorbaModule._ManagerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaModule.ManagerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaModule.ManagerInterface)
      return (CorbaModule.ManagerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaModule._ManagerInterfaceStub stub = new CorbaModule._ManagerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
