package CorbaModule;

/**
* CorbaModule/ManagerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Monday, October 22, 2018 6:50:23 PM EDT
*/

public final class ManagerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaModule.ManagerInterface value = null;

  public ManagerInterfaceHolder ()
  {
  }

  public ManagerInterfaceHolder (CorbaModule.ManagerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaModule.ManagerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaModule.ManagerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaModule.ManagerInterfaceHelper.type ();
  }

}
