package CorbaModule;

/**
* CorbaModule/ProjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Monday, October 22, 2018 6:50:23 PM EDT
*/

public final class ProjectHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaModule.Project value = null;

  public ProjectHolder ()
  {
  }

  public ProjectHolder (CorbaModule.Project initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaModule.ProjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaModule.ProjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaModule.ProjectHelper.type ();
  }

}
