package CorbaModule;


/**
* CorbaModule/Project.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Tuesday, October 23, 2018 at 9:46:16 PM Eastern Daylight Time
*/

public final class Project implements org.omg.CORBA.portable.IDLEntity
{
  public String projectId = null;
  public String clientName = null;
  public String projectName = null;

  public Project ()
  {
  } // ctor

  public Project (String _projectId, String _clientName, String _projectName)
  {
    projectId = _projectId;
    clientName = _clientName;
    projectName = _projectName;
  } // ctor

	public String getProjectId() {
		return projectId;
	}

	public String getClientName() {
		return clientName;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectId(String id) {
		projectId = id;
	}

	public void setClientName(String cName) {
		clientName = cName;
	}

	public void setProjectName(String pName) {
		projectName = pName;
	}

} // class Project
