package CorbaModule;


/**
* CorbaModule/Project.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaModule.idl
* Monday, October 22, 2018 6:50:23 PM EDT
*/

public final class Project implements org.omg.CORBA.portable.IDLEntity
{
  public String projectId = null;
  public String clientName = null;
  public String projectName = null;

  public Project ()
  {
  } // ctor

  public Project (String _projectId, String _clientName, String _projectName)
  {
    projectId = _projectId;
    clientName = _clientName;
    projectName = _projectName;
  } // ctor

} // class Project
